version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: country-encyclopedia
        container_name: country-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - country-network
        depends_on:
            - db

    db:
        image: postgres:14
        container_name: country-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - country-network

    nginx:
        image: nginx:alpine
        container_name: country-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - country-network
        depends_on:
            - app

networks:
    country-network:
        driver: bridge

volumes:
    dbdata: 