services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: country-encyclopedia
        container_name: country-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - country-network
        # removed depends_on

    nginx:
        image: nginx:alpine
        container_name: country-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - country-network
        depends_on:
            - app

networks:
    country-network:
        driver: bridge
